spring:
  jpa:
    show-sql: false

logging:
  level:
    root: INFO
    org.prography: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.springframework.web.servlet.PageNotFound: WARN
    org.springframework.dao: ERROR