CREATE TABLE curriculums (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    chapter_label VARCHAR(50) NOT NULL,
    session_title_template VARCHAR(100) NOT NULL,
    display_order INT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE badge_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level INT NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    required_completed_sessions INT NOT NULL
);

INSERT INTO curriculums (code, name, chapter_label, session_title_template, display_order) VALUES
    ('INTEGERS_RATIONALS', '정수와 유리수', '1단원 정수와 유리수', '정수와 유리수의 세계', 1),
    ('LINEAR_EQUATIONS', '일차방정식', '2단원 일차방정식', '일차방정식의 세계', 2),
    ('FRACTION_CALC', '분수의 계산', '3단원 분수', '분수의 세계', 3),
    ('GEOMETRY_BASICS', '도형의 기초', '4단원 도형', '도형의 세계', 4),
    ('PROPORTION', '비례와 반비례', '5단원 비례', '비례와 반비례의 세계', 5),
    ('STATISTICS', '통계의 기초', '6단원 통계', '통계의 세계', 6),
    ('DECIMAL_DIVISION', '소수의 나눗셈', '7단원 소수', '소수의 세계', 7),
    ('RULES_CORRESPONDENCE', '규칙과 대응', '8단원 규칙', '규칙과 대응의 세계', 8);

INSERT INTO badge_levels (level, name, required_completed_sessions) VALUES
    (1, '새싹 선생님', 0),
    (2, '똑똑한 선생님', 1),
    (3, '멋진 선생님', 3),
    (4, '최고의 선생님', 5);