CREATE TABLE lesson_topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curriculum_id BIGINT NOT NULL REFERENCES curriculums (id),
    sequence INT NOT NULL,
    title VARCHAR(200) NOT NULL,
    subtitle VARCHAR(100),
    topic_type VARCHAR(20) NOT NULL,
    gnb_title VARCHAR(100) NOT NULL,
    UNIQUE (curriculum_id, sequence)
);

CREATE TABLE lesson_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_topic_id BIGINT NOT NULL REFERENCES lesson_topics (id),
    phase VARCHAR(20) NOT NULL,
    bubble_text TEXT NOT NULL,
    wrong_answer_html TEXT
);

CREATE TABLE hint_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_topic_id BIGINT NOT NULL REFERENCES lesson_topics (id),
    phase VARCHAR(20) NOT NULL,
    content_json TEXT NOT NULL,
    UNIQUE (lesson_topic_id, phase)
);

INSERT INTO lesson_topics (curriculum_id, sequence, title, subtitle, topic_type, gnb_title)
SELECT c.id, 1, '분수란?', '개념이해', 'CONCEPT', '3. 분수의 개념'
FROM curriculums c WHERE c.code = 'FRACTION_CALC';

INSERT INTO lesson_topics (curriculum_id, sequence, title, subtitle, topic_type, gnb_title)
SELECT c.id, 2, '분수의 덧셈과 뺄셈', '계산과정', 'CALCULATION', '3. 분수의 덧셈과 뺄셈'
FROM curriculums c WHERE c.code = 'FRACTION_CALC';

INSERT INTO lesson_questions (lesson_topic_id, phase, bubble_text, wrong_answer_html)
SELECT lt.id, 'INTRO', '선생님, 분수는 그냥 숫자랑 어떻게 달라요?', NULL
FROM lesson_topics lt
JOIN curriculums c ON lt.curriculum_id = c.id
WHERE c.code = 'FRACTION_CALC' AND lt.sequence = 1;

INSERT INTO lesson_questions (lesson_topic_id, phase, bubble_text, wrong_answer_html)
SELECT lt.id, 'REACTION', '아하! 그럼 2/5 더하기 1/5는 <strong>3/10</strong>이죠?', '3/10'
FROM lesson_topics lt
JOIN curriculums c ON lt.curriculum_id = c.id
WHERE c.code = 'FRACTION_CALC' AND lt.sequence = 2;

INSERT INTO hint_notes (lesson_topic_id, phase, content_json)
SELECT lt.id, 'INTRO',
    '{"header":{"chapter":"제 3장","title":"분수의 개념"},"sections":[{"id":"q1","title":"Q1. 분수란?","bodyHtml":"전체를 똑같이 나눈 것 중, <strong>일부분</strong>을 나타내는 수","highlight":false}]}'
FROM lesson_topics lt
JOIN curriculums c ON lt.curriculum_id = c.id
WHERE c.code = 'FRACTION_CALC' AND lt.sequence = 1;

INSERT INTO hint_notes (lesson_topic_id, phase, content_json)
SELECT lt.id, 'REACTION',
    '{"header":{"chapter":"제 3장","title":"분수의 덧셈과 뺄셈"},"sections":[{"id":"rule-denominator","title":"핵심 규칙","bodyHtml":"분모(아래)는 절대 더하지 않고 그대로 둡니다!","highlight":true},{"id":"rule-numerator","title":"","bodyHtml":"분자(위)끼리만 더해야 합니다","highlight":true}]}'
FROM lesson_topics lt
JOIN curriculums c ON lt.curriculum_id = c.id
WHERE c.code = 'FRACTION_CALC' AND lt.sequence = 2;