CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    timezone VARCHAR(50) NOT NULL DEFAULT 'Asia/Seoul',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_profiles (
    user_id BIGINT PRIMARY KEY REFERENCES users (id),
    badge_level_id BIGINT NOT NULL REFERENCES badge_levels (id),
    total_coins INT NOT NULL DEFAULT 0,
    completed_session_count INT NOT NULL DEFAULT 0,
    onboarding_completed BOOLEAN NOT NULL DEFAULT FALSE,
    onboarding_step INT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_curriculums (
    user_id BIGINT PRIMARY KEY REFERENCES users (id),
    curriculum_id BIGINT NOT NULL REFERENCES curriculums (id),
    progress_percent INT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_schedules (
    user_id BIGINT PRIMARY KEY REFERENCES users (id),
    frequency_per_week INT NOT NULL,
    lesson_time TIME NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_schedule_days (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_schedule_id BIGINT NOT NULL REFERENCES user_schedules (user_id),
    day_of_week VARCHAR(3) NOT NULL,
    selected_order INT NOT NULL,
    UNIQUE (user_schedule_id, day_of_week)
);