CREATE TABLE tutoring_sessions (
    id VARCHAR(36) PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    curriculum_id BIGINT NOT NULL REFERENCES curriculums (id),
    status VARCHAR(20) NOT NULL,
    current_phase VARCHAR(20),
    session_date DATE NOT NULL,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    primary_topic_title VARCHAR(200),
    coins_awarded INT,
    badge_level_up BOOLEAN,
    progress_after INT,
    reward_status VARCHAR(20),
    reward_acknowledged_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_tutoring_sessions_user_date ON tutoring_sessions (user_id, session_date);
CREATE INDEX idx_tutoring_sessions_user_status ON tutoring_sessions (user_id, status);

CREATE TABLE session_topic_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL REFERENCES tutoring_sessions (id),
    lesson_topic_id BIGINT NOT NULL REFERENCES lesson_topics (id),
    sequence INT NOT NULL,
    title VARCHAR(200) NOT NULL,
    subtitle VARCHAR(100),
    topic_type VARCHAR(20) NOT NULL,
    UNIQUE (session_id, sequence)
);

CREATE TABLE coin_ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    session_id VARCHAR(36) NOT NULL UNIQUE REFERENCES tutoring_sessions (id),
    amount INT NOT NULL,
    type VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);