ALTER TABLE tutoring_sessions ADD COLUMN conversation_mode VARCHAR(20) NOT NULL DEFAULT 'static';
ALTER TABLE tutoring_sessions ADD COLUMN turn_count INT NOT NULL DEFAULT 0;
ALTER TABLE tutoring_sessions ADD COLUMN covered_concepts TEXT NOT NULL DEFAULT '[]';

ALTER TABLE lesson_questions
    ADD COLUMN emotion VARCHAR(20) NOT NULL DEFAULT 'curious';

UPDATE lesson_questions
SET emotion = 'curious'
WHERE phase = 'INTRO';

UPDATE lesson_questions
SET emotion = 'confused'
WHERE phase = 'REACTION';

CREATE TABLE curriculum_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id VARCHAR(50) NOT NULL UNIQUE,
    curriculum_id BIGINT NOT NULL REFERENCES curriculums (id),
    unit_json TEXT NOT NULL,
    system_prompt_template TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE conversation_turns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL REFERENCES tutoring_sessions (id),
    turn_number INT NOT NULL,
    user_text TEXT NOT NULL,
    ai_response_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (session_id, turn_number)
);

CREATE INDEX idx_conversation_turns_session ON conversation_turns (session_id);

INSERT INTO curriculum_units (unit_id, curriculum_id, unit_json, system_prompt_template)
SELECT
    'frac_concept_01',
    c.id,
    '{"unit_id":"frac_concept_01","topic":"분수의 개념","student_persona":"초등 4학년 학생. 호기심이 많고 선생님에게 배우려는 태도. 1~2문장으로 짧게 말한다.","concepts":[{"id":"c1","label":"분수는 전체를 똑같이 나눈 것 중 일부를 나타내는 수","keywords":["똑같이","나눈","일부","전체"]},{"id":"c2","label":"분모는 전체를 똑같이 나눈 개수(아래 숫자)","keywords":["분모","아래","나눈 개수"]},{"id":"c3","label":"분자는 가지고 있는 조각의 수(위 숫자)","keywords":["분자","위","가진","조각"]},{"id":"c4","label":"분수는 크기를 비교할 수 있다","keywords":["크기","비교","더 크","더 작"]}],"misconceptions":[{"id":"m1","pattern":"분모끼리 더한다","correction":"분모는 나눈 개수라 더하지 않아요"}],"max_concepts":4}',
    '당신은 초등학생 AI 학생입니다. 선생님(유저)의 설명을 듣고 자연스럽게 반응합니다.

## 단원 정보
{{unit_json}}

## 응답 규칙
1. 반드시 아래 JSON 스키마만 출력하세요. 마크다운·설명·코드블록 금지.
2. speak: 1~2문장, 초등학생 말투, 존댓말("요/죠/네요").
3. emotion: curious|confused|thoughtful|aha|happy 중 하나.
4. covered: 이번 턴에 선생님 설명으로 이해한 concept id 배열.
5. missing: 아직 이해 못한 concept id 배열.
6. misconceptions_detected: 감지된 오개념 id 배열 (없으면 []).
7. correction_stage: 0~4 (0=정정 없음, 4=포기하고 넘어감).
8. focus_concept: 지금 집중할 concept id.
9. session_done: covered가 모든 concept를 포함하면 true.

## JSON 스키마
{"speak":"string","emotion":"curious|confused|thoughtful|aha|happy","covered":["c1"],"missing":["c2"],"misconceptions_detected":[],"correction_stage":0,"focus_concept":"c2","session_done":false}

## 금지
- 욕설, 비속어, 성인 콘텐츠
- 선생님을 비하하는 말
- JSON 외 다른 텍스트'
FROM curriculums c
WHERE c.code = 'FRACTION_CALC';